### ISSUE TITLE
Use of chromosome number in findCpGsnearSNP

### ISSUE THREAD

**Issue by ellisifnygaard** [jromanowska/HaplinMethyl#1]
I have 2 thoughts regarding the use of chromosome number in `findCpGsnearSNP`:  

**1**
For `findCpGsnearSNP` to produce correct results, the user must be careful to ensure that the CpGs in `cpgs` are all on the same chromosome as the SNP. I think the function would be more user-friendly if this was clearly highlighted in the description. It is kind of obvious, but an explicit reminder could be helpful. 

**2**
If I understand the data correctly, you cannot tell if the CpGs and the SNP are on the same chromosome by looking exclusively at the values of `snp$coord` and `cpgs$coord`. If something goes wrong, it might not be immediately obvious or discovered right away.  
If the user has a list containing pairs of `snp` and `cpgs` that are mismatched due to a mistake, it could be useful if `findCpGsnearSNP`  alerted the user about this.  

The following could act as an extra preventive measure against CpGs from a particular chromosome being matched up with a SNP on a different chromosome:
  
- `cpgs` must contain an additional column/element: `cpgs$chr`
- the function checks whether `cpgs$chr == snp$chr`  and produces a stop message if they do not match.
  
  
**1** is quick and easy to implement, but **2** is a little more work.

**Comment by jromanowska** [comment]
True. I was always using it with CpGs divided into chromosomes, and since the function says "findCpGs _near_ SNP", this is how it should be. You might just add a sentence about it in the documentation, as you suggested in point **1**

Thank you for looking into it!

**Comment by ellisifnygaard** [comment]
Will do 👍
