### ISSUE TITLE
Incorrect version of package encoded in DESCRIPTION file?

### ISSUE THREAD

**Issue by ellisifnygaard** [jromanowska/HaplinMethyl#13]
I just read in a tutorial somewhere that the version of a package is encoded in the DESCRIPTION file. In the current DESCRIPTION file, it says `Version: 0.1`:
https://github.com/jromanowska/HaplinMethyl/blob/8ed57666704eeb06288e87abc6e72268b4c2ee55/DESCRIPTION#L2

But aren't we currently on version v0.2? https://github.com/jromanowska/HaplinMethyl/commit/8ed57666704eeb06288e87abc6e72268b4c2ee55

I think this is the reason why the the automatically generated file name when building a source package is "`HaplinMethyl_0.1.tar.gz`" (which confused me a little when I first noticed this a few days ago🤔 ).

**Comment by jromanowska** [comment]
This is important when we'll create a new release. I can change it :+1:

**Comment by jromanowska** [comment]
Solved in commit [7fc4afd](https://github.com/jromanowska/HaplinMethyl/commit/7fc4afdc0c45f38321896fb55323bf1d54dc9372)
