### ISSUE TITLE
Number of columns in cpgs argument

### ISSUE THREAD

**Issue by ellisifnygaard** [jromanowska/HaplinMethyl#2]
I think that 
1) *either* the description 
https://github.com/jromanowska/HaplinMethyl/blob/4944ded2c578ceb592800ea5745ac7997c9ea391/R/findCpGsnearSNP.R#L11
should clearly state that `cpgs` must contain only two elements/columns, and that they must be named "id" and "coord",
  
2) *or* this code  https://github.com/jromanowska/HaplinMethyl/blob/4944ded2c578ceb592800ea5745ac7997c9ea391/R/findCpGsnearSNP.R#L31
should be tweaked so that the IF statement evaluates to `FALSE` when `cpgs` has more elements/columns in addition to "cpgs$id" and "cpgs$coord", i.e. the function should not stop as long as `cpgs` has one column named `id` and one column `coord`.
  

If @jromanowska agrees, we should wait until issue #1 has been closed before we change anything 😊

**Comment by ellisifnygaard** [comment]
I have implemented option 1 and added a IF statement checking whether `cpgs` has 2 elements/columns or not.

**Comment by ellisifnygaard** [comment]
df9a12bb9db7124b1386b9098cbe8ed3e6a9221b
2f3ece51e590f7ba8076655cb910b12582428b4e
5863ba750d762fff06894358ce3f3d8973d82364

**Comment by jromanowska** [comment]
Thank yoU!
