### ISSUE TITLE
envDataSubset() results in files with "_gen" suffix instead of "_env" suffix

### ISSUE THREAD

**Issue by ellisifnygaard** [jromanowska/HaplinMethyl#8]
Due to this line: https://github.com/jromanowska/HaplinMethyl/blob/cd64db9cb6765496e83f416b11e6d7944ab7240b/R/envDataSubset.R#L35

`envDataSubset()` results in the following file names:  
  
- `*file.out*_gen.ffData`, and
- `*file.out*_gen.RData`. 

I think this can be easily fixed by adding `, root = "env"` to the arguments supplied to the `Haplin:::f.make.out.filename()` function on lines 35 and 36. Ref. line 61-63 in `envDataRead()`:  
````
	files.list <- Haplin:::f.make.out.filename(
		file.in, file.out, dir.out = dir.out,
		root = "env", overwrite = overwrite )
```

**Comment by ellisifnygaard** [comment]
I just tested envDataSubset() on real EWAS data on the safe server and can confirm that this issue is fixed :)

**Comment by jromanowska** [comment]
Thank you, Ellisif!
